import { DomainTaxonomy } from './types';

export const domainTaxonomy: DomainTaxonomy = {
  payer: [
    {
      name: '834 Enrollment',
      eventDriver: 'memberChurn',
      expansion: 1.5,
      versioning: 1.25,
      billable: true,
      cdcEligible: true,
    },
    {
      name: '837 Claims Intake',
      eventDriver: 'claims',
      eventRatio: 1.0,
      expansion: 7.5,
      versioning: 1.05,
      billable: true,
      cdcEligible: true,
    },
    {
      name: '835 ERA/Payments',
      eventDriver: 'claims',
      eventRatio: 0.9,
      expansion: 4,
      versioning: 1.05,
      billable: true,
      cdcEligible: true,
    },
    {
      name: '278 Authorizations',
      eventDriver: 'authRate',
      expansion: 2.5,
      versioning: 1.15,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Accumulators',
      eventDriver: 'claims',
      eventRatio: 0.3,
      expansion: 1.25,
      versioning: 1.2,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Provider Network',
      eventDriver: 'providerChurn',
      expansion: 2,
      versioning: 1.05,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'HEDIS/Quality',
      eventDriver: 'members',
      eventRatio: 0.02,
      expansion: 2,
      versioning: 1.02,
      billable: true,
      cdcEligible: false,
    },
    {
      name: 'Risk Adjustment',
      eventDriver: 'members',
      eventRatio: 0.03,
      expansion: 1.5,
      versioning: 1.1,
      billable: true,
      cdcEligible: false,
    },
    {
      name: 'Clinical Integration',
      eventDriver: 'members',
      eventRatio: 0.1,
      expansion: 4,
      versioning: 1.05,
      billable: true,
      cdcEligible: true,
    },
  ],
  tpa: [
    {
      name: '834 Enrollment',
      eventDriver: 'memberChurn',
      expansion: 1.5,
      versioning: 1.25,
      billable: true,
      cdcEligible: true,
    },
    {
      name: '837 Claims Processing',
      eventDriver: 'claims',
      eventRatio: 1.0,
      expansion: 90, // Claim → lines (4.5x) × business logic (20x) = full claim lifecycle with processing, audit, versions
      versioning: 1.0,
      billable: true,
      cdcEligible: true,
    },
    {
      name: '835 ERA/Payments',
      eventDriver: 'claims',
      eventRatio: 0.9,
      expansion: 25, // ERA processing with full payment reconciliation, GL integration, bank file generation
      versioning: 1.0,
      billable: true,
      cdcEligible: true,
    },
    {
      name: '278 Authorizations',
      eventDriver: 'authRate',
      expansion: 2.5,
      versioning: 1.15,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Accumulators',
      eventDriver: 'claims',
      eventRatio: 0.3,
      expansion: 1.25,
      versioning: 1.2,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Employer Funding',
      eventDriver: 'employers',
      eventRatio: 12,
      expansion: 3,
      versioning: 1.0,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Admin Billing',
      eventDriver: 'employers',
      eventRatio: 12,
      expansion: 3,
      versioning: 1.0,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Bank Reconciliation',
      eventDriver: 'employers',
      eventRatio: 20,
      expansion: 1.5,
      versioning: 1.0,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'COB/Subrogation',
      eventDriver: 'claims',
      eventRatio: 0.08,
      expansion: 5,
      versioning: 1.2,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Provider Network',
      eventDriver: 'providerChurn',
      expansion: 2,
      versioning: 1.05,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Repricing/Networks',
      eventDriver: 'claims',
      eventRatio: 1.0,
      expansion: 2,
      versioning: 1.0,
      billable: true,
      cdcEligible: true,
    },
  ],
  provider: [
    {
      name: 'ADT Events',
      eventDriver: 'admissions',
      eventRatio: 1,
      expansion: 1.5,
      versioning: 1.02,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Orders (ORM)',
      eventDriver: 'claims',
      eventRatio: 2.0,
      expansion: 2,
      versioning: 1.05,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Results (ORU)',
      eventDriver: 'claims',
      eventRatio: 1.5,
      expansion: 3,
      versioning: 1.05,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Charge Capture',
      eventDriver: 'claims',
      eventRatio: 1.2,
      expansion: 3,
      versioning: 1.1,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Coding/DRG',
      eventDriver: 'claims',
      eventRatio: 0.3,
      expansion: 2,
      versioning: 1.1,
      billable: true,
      cdcEligible: false,
    },
    {
      name: '837 Generation',
      eventDriver: 'claims',
      eventRatio: 1.0,
      expansion: 7.5,
      versioning: 1.05,
      billable: true,
      cdcEligible: true,
    },
    {
      name: '835 Posting',
      eventDriver: 'claims',
      eventRatio: 0.9,
      expansion: 4,
      versioning: 1.05,
      billable: true,
      cdcEligible: true,
    },
    {
      name: 'Denials Management',
      eventDriver: 'claims',
      eventRatio: 0.15,
      expansion: 6,
      versioning: 1.3,
      billable: true,
      cdcEligible: false,
    },
    {
      name: 'Patient Finance',
      eventDriver: 'claims',
      eventRatio: 0.2,
      expansion: 3,
      versioning: 1.1,
      billable: true,
      cdcEligible: true,
    },
  ],
};

// Default pricing inputs
export const defaultInputs: import('./types').PricingInputs = {
  // Customer Profile
  orgType: 'tpa',
  memberLives: 250000,
  memberChurn: 2,
  providers: 5000,
  employers: 50,

  // Volume Drivers
  claimsVolume: 2500000, // 250K members × 10 claims/member/year = 2.5M claims/year
  rxVolume: 5000000, // 250K members × 20 Rx fills/member/year = 5M Rx/year
  authRate: 12,
  growthRate: 10,

  // Implementation
  smallTrades: 5,
  mediumTrades: 8,
  largeTrades: 3,
  dbReplication: 0,
  hasDiscovery: true,

  // Settings
  cdcTimeline: 0,
  cdcCoverage: 0,
  hasPremiumSLA: false,

  // Margins
  implMargin: 40,
  platformCostPct: 30,
  dataCostPct: 25,
  supportCostPct: 15,

  // Advanced
  loadedCostPerHour: 150,
  dataCostPer1M: 47000,
  globalRowMultiplier: 1.0,
  pipelineMultiplier: 4.0, // Standard: Raw → Bronze → Silver → Gold
};
